import { VocabularyCard } from "./types";

export const DEFAULT_VOCABULARY_CARDS: VocabularyCard[] = [
  {
    id: "1",
    word: "Serendipity",
    pronunciation: "/ˌserənˈdipədē/",
    partOfSpeech: "noun",
    definition: "The occurrence of events by chance in a happy, fortunate, or beneficial way.",
    example: "We found the charming little hidden bookstore by pure serendipity while walking in the rain.",
    customContext: "Reminds me of my favorite coffee shop that I discovered when I took a wrong turn last summer.",
    imageUrl: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
    colorTheme: "rose",
    createdAt: 1716250000000,
  },
  {
    id: "2",
    word: "Petrichor",
    pronunciation: "/ˈpeˌtrīkôr/",
    partOfSpeech: "noun",
    definition: "A pleasant, earthy smell that frequently accompanies the first rain after a long period of warm, dry weather.",
    example: "The rich petrichor filled the air as the heavy summer raindrops hit the dusty pavement.",
    customContext: "The comforting smell of the dry soil outside my childhood window during first rain.",
    imageUrl: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=800&q=80",
    colorTheme: "emerald",
    createdAt: 1716250100000,
  },
  {
    id: "3",
    word: "Ephemeral",
    pronunciation: "/əˈfemərəl/",
    partOfSpeech: "adjective",
    definition: "Lasting for a very short, fleeting time; transient or momentary.",
    example: "The cherry blossoms are beautiful but ephemeral, lasting only a few precious days before scattering in the wind.",
    customContext: "Like a beautiful sunset or morning dew. Appreciate the moments before they fade away.",
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80",
    colorTheme: "violet",
    createdAt: 1716250200000,
  },
  {
    id: "4",
    word: "Mellifluous",
    pronunciation: "/məˈlifloowəs/",
    partOfSpeech: "adjective",
    definition: "Sweet, musical, or smooth; incredibly pleasant and soothing to hear.",
    example: "The cello soloist's mellifluous tone resonated deeply, captivating the entire silent concert hall.",
    customContext: "Sounds like the soft sound of acoustic guitar, cello, or rain tapping gently on the roof.",
    imageUrl: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80",
    colorTheme: "amber",
    createdAt: 1716250300000,
  },
  {
    id: "5",
    word: "Solitude",
    pronunciation: "/ˈsäləˌt(y)o͞od/",
    partOfSpeech: "noun",
    definition: "The state or situation of being alone, especially in a lonely, quiet, and peaceful way that brings comfort.",
    example: "She savored the quiet solitude of the early morning forest before the rest of the world woke up.",
    customContext: "That peaceful half-hour before checking notifications where I can just breathe.",
    imageUrl: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&w=800&q=80",
    colorTheme: "sky",
    createdAt: 1716250400000,
  },
  {
    id: "6",
    word: "Luminescence",
    pronunciation: "/ˌlo͞oməˈnesəns/",
    partOfSpeech: "noun",
    definition: "The low-temperature emission of light, such as that caused by chemical reactions or biological organisms.",
    example: "The bioluminescent phytoplankton gave the dark night sea a magical, glowing blue luminescence.",
    customContext: "Reminds me of fireflies in summer nights, glowing softly in the dark tree canopies.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    colorTheme: "indigo",
    createdAt: 1716250500000,
  },
];
